YIMBY:
    - restaurant
    - pharmacy
    - local_government_office
    - gym
    - school
    - church
    - university
    - hospital
    - mosque
    - hindu_temple
    - library
    - doctor
    - synagogue
    - city_hall
    - dentist
    - doctor
    - trainsit_station
    - bus_station
    - park
    - subway_station

NIMBY:
    - airport
    - gas_station
    - convenience_store
    - shopping_mall
    - night_club
    - rv_park
    - parking
    - liquor_store
    - casino
    - bakery
    - bar
    - meal_takeaway
    - meal_delivery
    - parking
    - police
    - storage
    - movie_theater
    - laundry
    - bowling_alley
    - movie_rental

APIS:
    google_place_api: https://maps.googleapis.com/maps/api/place/nearbysearch/json
    google_place_api_key: AIzaSyCAYAAI4o6mhETaz_YUrGvTVTQi9ePDKbU
    breezometer_aqi_api: http://api.breezometer.com/baqi/?
    breezometer_aqi_api_key: 906d4d728056496b85b059e335a17a18
